# Generated by Django 4.2.3 on 2023-07-11 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gaari', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='autos',
            options={'verbose_name_plural': 'Autos'},
        ),
        migrations.AlterModelOptions(
            name='make',
            options={'verbose_name_plural': 'Brands'},
        ),
        migrations.AddField(
            model_name='autos',
            name='image',
            field=models.FileField(null=True, upload_to='images'),
        ),
    ]
