# Generated by Django 4.2.3 on 2023-07-11 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gaari', '0002_alter_autos_options_alter_make_options_autos_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autos',
            name='image',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
