# Generated by Django 4.2.3 on 2023-07-13 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gaari', '0005_review_created_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='make',
            name='image',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
