# Generated by Django 4.2.3 on 2023-07-13 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gaari', '0010_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='reciever',
            new_name='receiver',
        ),
    ]
